### ISSUE TITLE
【疑问 & 建议】D3D12如何支持多个窗口（HWND）？

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [GamebabyRockSun/GRSD3D12Sample#2]
无论在微软的示例中，和作者的示例中，还是一些游戏引擎的示例中，都没讲过如何渲染到多个窗口。

听我的朋友给我说过，要想支持多窗口，最好就是一条线程一个窗口，不然会很卡。

可我想要的是如何单线程多窗口的实现，希望作者能够普及一下，谢谢。

**Comment by ChinaChenMingQuan** [comment]
作者响应时间过长，吐了，再见！

**Comment by ChinaChenMingQuan** [comment]
作者或许不在，或许也不会有解决方案，又或许压根就不想理。

我要在这留下答案，以防后来者遇到类似的迷惑不能解决。（路程太心酸，作者不理人，谷歌找答案，全是DX11的解决方案，在官方微软提疑问，无人问津）

不满足2D的GUI，想写3D的GUI的后来者们，最后我找到了一个暴力解决方案。

1. 在单个进程，单个线程内，如果不需要垂直同步，浪费一点电力的话，每个窗口（HWND）创建绑定SwapChain，CommandQueue->ExecuteCommandLists，等待GPU画完，然后每个窗口都调用一次SwapChain->Present(0, 0)即可。不知道是不是硬件驱动有些问题，我的老显卡GTX650，需要在调用完所有Present后还要再等一次GPU，等GPU画完才能继续渲染下一帧，否则我的进程会崩溃。（备注：如果需要垂直同步的话，把SwapChain->Present(0, 0)改成SwapChain->Present(1, 0)即可，但是窗口会变得有点卡。。。）

2. 在单个进程，多个线程内，每个线程只允许有一个窗口，但是要创建多个Device，可行是可行，会有点占内存，性能有点惨不忍睹，而且这个方法官方微软不推荐！！！

3. 在单个进程，单个线程，单个窗口内，自己画多个窗口吧，这或许是最简单，也是最难的了，你还要模拟窗口的消息队列，尺寸调整，窗口拖拽，我TM又不是写操作系统的，淦！！！

4. 暴力美学，多个进程，每个进程一个窗口，虽然每个窗口需要通讯，但是性能和效果却非常的出色，我TM的惊呆了！！！

**Comment by GamebabyRockSun** [comment]
不好意思，一直没注意这个问题，这个其实不复杂，多线程是一种方式，单线程多窗口也可以。

**Comment by GamebabyRockSun** [comment]
多线程的时，要注意窗口消息队列就分开了，可能还要面临多线程间通讯的问题，会比较麻烦。单线程多窗口卡顿，我估计是因为写的消息循环不对头导致的，如果你用的dx12的话，无非就是多创建几个渲染交换链，可以试一下单命令队列多个交换链组合方式，或者多个命令队列，多个交换链的组合方式，同时因为dx12本质上是异步运行的特征，卡顿问题应该是可以通过编程方式克服的，具体要看代码编写。

**Comment by GamebabyRockSun** [comment]
你说的 第1种方式，我建议你多个present之后统一等待一次就完了，等我回头搞个原型出来上传到示例里，你的想法是个好点子。多个进程 多个窗口，这个没啥，就是看你硬件性能怎么样了。
