### ISSUE TITLE
报错：无效参数：E_INVALIDARG (0x80070057)

### ISSUE THREAD

**Issue by hnzkliuwei** [GamebabyRockSun/GRSD3D12Sample#3]
https://github.com/GamebabyRockSun/GRSD3D12Sample/blob/fa15efa6be736724a88188e25e6493e4c76b6dfc/13-ShowGIFAndResourceStatus/13-ShowGIFAndResourceStatus.cpp#L726
在 win10 NVIDIA Quadro P4000上跑此行报上述错误

**Comment by GamebabyRockSun** [comment]
你打开项目属性窗口，看下你的windk版本，换下最新的试试，或者更新下驱动试试。
