### ISSUE TITLE
运行闪退

### ISSUE THREAD

**Issue by WANGNING0501** [GamebabyRockSun/GRSD3D12Sample#4]
您好，想问下 这个例子在我电脑上运行的时候 也不报错  但是一直闪退是什么问题呢 ？我应该考虑哪方面的问题去解决

**Comment by GamebabyRockSun** [comment]
嗯，从创建DXGI跟踪一下看看，八成是因为D3D12支持的问题，然后看下VS2019输出窗口里的内容，例子可能对显卡有要求，最好是GTX10系以上的显卡，还有更新驱动程序，集显的话我都没有测试，不好意思，光顾着独显了。

**Comment by GamebabyRockSun** [comment]
注意 靠前的几个例子遍历显卡都是老方式循环，为了调试我把循环序号调成1了，如果你的电脑只有一块显卡闪退可能是因为根本没有序号1的显卡造成的，你改回从0开始遍历显卡试试。
